name: prontuario_medico
description: "Um sistema de gerenciamento de prontuários acadêmicos."

# Previne a publicação acidental em pub.dev.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

# Seção de Dependências
# ================================================================
dependencies:
  flutter:
    sdk: flutter

  # Conexão com o backend e banco de dados
  supabase_flutter: ^2.3.1

  # Utilitários e Funcionalidades
  intl: ^0.18.1                   # Para formatação de datas
  file_picker: ^6.1.1             # Para selecionar arquivos do computador
  url_launcher: ^6.2.1            # Para abrir links (como o de download)
  pdf: ^3.10.7                    # Para criar documentos PDF
  printing: ^5.11.1               # Para visualizar e imprimir PDFs
  timezone: ^0.9.2                # Para trabalhar com fusos horários
  path_provider: ^2.1.1            # Para acessar o sistema de arquivos

  # Ícones padrão do Material Design
  cupertino_icons: ^1.0.2

# Seção de Dependências de Desenvolvimento (para testes, etc.)
# ================================================================
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Ferramenta para garantir boas práticas de código
  flutter_lints: ^2.0.0

# Seção de Configurações Específicas do Flutter
# ================================================================
flutter:
  # Ativa o uso do Material Design
  uses-material-design: true


  # Para declarar fontes personalizadas (exemplo comentado)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro-Bold.ttf
  #         weight: 700