name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Altere para a sua branch principal, se não for 'main'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x.x' # Use a versão do Flutter que você está usando, ex: '3.19.6'
          channel: 'stable'

      - name: Get Dependencies
        run: flutter pub get

      - name: Build Web Project
        run: flutter build web --release --base-href /prontuario/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          keep_files: false